# config/packages/validator.yaml
framework:
    validation:
        enabled: true

# Configuration spécifique à l'environnement de test
when@test:
    framework:
        validation:
            enabled: true
            not_compromised_password: false
